import { Heading, SimpleGrid } from '@chakra-ui/react';
import { GetStaticProps, NextPage } from 'next';
import Head from 'next/head';
import ProjectCard from '../components/project/ProjectCard';
import request from '../lib/datocms';

type ProjectsPageProps = {
  allProjects: Array<Project>;
};

const Projects: NextPage<ProjectsPageProps> = ({ allProjects }) => {
  return (
    <>
      <Head>
        <title>projects | alistair&apos;s corner</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Heading pb={2}>projects</Heading>
        <SimpleGrid columns={{ base: 1, md: 2, lg: 3 }} columnGap={2}>
          {allProjects.map((project) => (
            <ProjectCard key={project.id} project={project} />
          ))}
        </SimpleGrid>
      </main>
    </>
  );
};

export const getStaticProps: GetStaticProps = async () => {
  const { allProjects } = await request({
    query: `{
      allProjects {
        id
        title
        image {
          id
          url(imgixParams: {auto: format, q: 80, w: 800, h: 600})
          alt
        }
        description
        link
        githubLink
        _status
        _firstPublishedAt
      }
    }
    `,
  });

  return { props: { allProjects }, revalidate: 20 };
};

export default Projects;
