---
label: Project
hide_body: false
fields:
- name: title
  type: text
  config:
    required: true
  label: Title
  description: Title of the project
- name: image
  type: file
  config:
    maxSize: 64
  label: Image
  description: Featured image
